Category.create(name: '病院', code: 'hospital', sort_num: 1, created_at: Time.current, updated_at: Time.current)
Category.create(name: '薬', code: 'medicine',sort_num: 2, created_at: Time.current, updated_at: Time.current)
Category.create(name: '赤ちゃん・育児', code: 'child_care',sort_num: 3, created_at: Time.current, updated_at: Time.current)
Category.create(name: '子育て・家族', code: 'family',sort_num: 4, created_at: Time.current, updated_at: Time.current)
Category.create(name: 'お仕事', code: 'job',sort_num: 5, created_at: Time.current, updated_at: Time.current)
Category.create(name: 'マネー', code: 'money',sort_num: 6, created_at: Time.current, updated_at: Time.current)