version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Decode dotenv file
          command: echo $ENV_FILE | base64 --decode > .env
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup npm install"
          command: docker exec -it $HEROKU_APP_NAME npm install
      - run:
          name: "before_test: setup npm run build:pro"
          command: docker exec -it $HEROKU_APP_NAME npm run build:pro
      - run:
          name: "before_test: setup db migration"
          command: docker exec -it $HEROKU_APP_NAME rails db:create db:migrate
      - run:
          name: "before_test: setup db seed"
          command: docker exec -it $HEROKU_APP_NAME rails db:seed:category db:seed:user
      - run:
          name: test
          command: docker exec -it -e RAILS_ENV=test $HEROKU_APP_NAME bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master